pipeline {
 agent any

 tools {
  // maven 'mvn' 
	maven 'maven3'
 }
 stages {
  stage('Build') {
   steps {
    sh 'mvn compile'
     //   sh 'mvn cargo:run -P tomcat90'
   }
  }
  stage('Test') {
   steps {
    sh 'mvn test'
   }
  }
 }
}
