pipeline {
 agent none

 tools {
  // maven 'mvn' 
	maven 'maven3'
 }
 stages {
  stage('Build') {
    agent {
        label master
      }
   steps {
    sh 'mvn compile'
     //   sh 'mvn cargo:run -P tomcat90'
   }
  }
  stage('Copy Artifact') {
    agent {
        label Test
      }
   steps {
    echo 'Copying'
   }
  }
 }
}
