node ('master') {
    def mvnHome
   stage('Preparation') {
      mvnHome = tool 'maven3'
   }
   stage('Build') {
      sh "'${mvnHome}/bin/mvn' clean install"
   }
   stage('Results') {
      archive 'target/*.jar'
   }   
}
