def err = null
try {
    node {
        // Main pipeline code goes here
         stage('Build') {
                echo 'Building..'
        }
        stage('Test') {
                echo 'Testing..'
         }
    }
} catch (caughtError) { //End of Try
    err = caughtError
    currentBuild.result = "FAILURE"
} finally {
   echo 'rieghrie'
    }
}

}
