pipeline {
    agent none
    stages {
        stage('Back-end') {
        
            steps {
               sh 'whoami'
              sh 'mvn --version'
            }
                  
        }
        stage('Front-end') {
             
              agent {
                docker { image 'node:7-alpine' }
            }
             steps {
              sh 'node --version'
            }
            
        }
    }
}
